import {
  BuyingRole,
  Industry,
  ProviderRunStatus,
  RfpStage,
  SourceType,
  TargetCategory,
} from "@prisma/client";

import type { MockSignalSeed } from "@/lib/types";

function isoDaysAgo(days: number) {
  return new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString();
}

export interface MockStakeholderSeed {
  name: string;
  title: string;
  function: string;
  buyingRole: BuyingRole;
  relevanceScore: number;
  suggestedMessageAngle: string;
}

export interface MockAccountSeed {
  name: string;
  website: string;
  industry: Industry;
  country: string;
  employeeCount: number;
  revenue: number;
  owner: string;
  notes: string;
  stakeholders: MockStakeholderSeed[];
}

export const MOCK_ACCOUNTS: MockAccountSeed[] = [
  {
    name: "Philips",
    website: "https://www.philips.com",
    industry: Industry.MEDTECH,
    country: "Netherlands",
    employeeCount: 68000,
    revenue: 19.4,
    owner: "EMEA Medtech Pod",
    notes: "Large enterprise account with field-heavy clinical and commercial motions.",
    stakeholders: [
      {
        name: "Eva van Dijk",
        title: "Head of Commercial Excellence, International Region",
        function: "Commercial Excellence",
        buyingRole: BuyingRole.PROGRAM_OWNER,
        relevanceScore: 91,
        suggestedMessageAngle: "Benchmarking field execution and compliant content workflows before platform decisions harden.",
      },
      {
        name: "Tom Rensen",
        title: "Director, CRM and Field Engagement",
        function: "Commercial Technology",
        buyingRole: BuyingRole.CHAMPION,
        relevanceScore: 88,
        suggestedMessageAngle: "Reducing friction across CRM, mobile field workflows, and HCP engagement.",
      },
      {
        name: "Marit Koster",
        title: "Category Manager, Customer Platforms",
        function: "Procurement",
        buyingRole: BuyingRole.PROCUREMENT,
        relevanceScore: 70,
        suggestedMessageAngle: "Confirming if a benchmark shortlist is already taking shape.",
      },
    ],
  },
  {
    name: "Merck Healthcare",
    website: "https://www.merckgroup.com",
    industry: Industry.PHARMA,
    country: "Germany",
    employeeCount: 62000,
    revenue: 22.1,
    owner: "DACH Pharma Pod",
    notes: "Good fit for commercial excellence, omnichannel, and CRM-adoption stories.",
    stakeholders: [
      {
        name: "Johanna Weiss",
        title: "VP Commercial Excellence",
        function: "Commercial Excellence",
        buyingRole: BuyingRole.ECONOMIC_BUYER,
        relevanceScore: 92,
        suggestedMessageAngle: "Helping affiliates compare field execution, HCP engagement, and coaching layers before global design choices lock in.",
      },
      {
        name: "Sven Reiter",
        title: "Global CRM Program Director",
        function: "Commercial Technology",
        buyingRole: BuyingRole.PROGRAM_OWNER,
        relevanceScore: 86,
        suggestedMessageAngle: "Aligning Salesforce, Veeva, and field enablement workflows into one operating motion.",
      },
      {
        name: "Anna Hoffmann",
        title: "Category Lead, Commercial Systems",
        function: "Procurement",
        buyingRole: BuyingRole.PROCUREMENT,
        relevanceScore: 68,
        suggestedMessageAngle: "Understanding whether supplier discovery is still open or already narrowed.",
      },
    ],
  },
  {
    name: "Novo Nordisk",
    website: "https://www.novonordisk.com",
    industry: Industry.PHARMA,
    country: "Denmark",
    employeeCount: 66000,
    revenue: 33.6,
    owner: "Nordics Pharma Pod",
    notes: "Strong fit for HCP engagement, Salesforce Life Sciences Cloud, and field coaching motions.",
    stakeholders: [
      {
        name: "Mads Kristensen",
        title: "Director, Omnichannel Capability",
        function: "Omnichannel",
        buyingRole: BuyingRole.PROGRAM_OWNER,
        relevanceScore: 89,
        suggestedMessageAngle: "Comparing HCP engagement and field orchestration approaches before vendor criteria are finalized.",
      },
      {
        name: "Helene Boe",
        title: "Senior Director, Commercial Technology",
        function: "Commercial Technology",
        buyingRole: BuyingRole.CHAMPION,
        relevanceScore: 84,
        suggestedMessageAngle: "Connecting CRM programs to rep readiness and compliant content usage.",
      },
      {
        name: "Jonas Lund",
        title: "Head of Procurement, Digital Platforms",
        function: "Procurement",
        buyingRole: BuyingRole.PROCUREMENT,
        relevanceScore: 64,
        suggestedMessageAngle: "Checking if a formal sourcing path is likely or still forming.",
      },
    ],
  },
  {
    name: "Novartis",
    website: "https://www.novartis.com",
    industry: Industry.PHARMA,
    country: "Switzerland",
    employeeCount: 78000,
    revenue: 45.4,
    owner: "Strategic Pharma Pod",
    notes: "Ideal account for CLM, omnichannel, and coaching-oriented narratives.",
    stakeholders: [
      {
        name: "Clara Meier",
        title: "Global Head of Customer Engagement Platforms",
        function: "Customer Engagement",
        buyingRole: BuyingRole.ECONOMIC_BUYER,
        relevanceScore: 93,
        suggestedMessageAngle: "Sharing how global teams benchmark HCP engagement stacks before formal procurement concludes.",
      },
      {
        name: "Lukas Steiner",
        title: "Program Lead, Field Force Effectiveness",
        function: "Commercial Excellence",
        buyingRole: BuyingRole.CHAMPION,
        relevanceScore: 87,
        suggestedMessageAngle: "Improving rep readiness, CRM adoption, and content governance in a single workflow layer.",
      },
      {
        name: "Nina Graf",
        title: "Procurement Lead, Commercial Applications",
        function: "Procurement",
        buyingRole: BuyingRole.PROCUREMENT,
        relevanceScore: 71,
        suggestedMessageAngle: "Confirming whether the shortlist is still open to benchmark vendors.",
      },
    ],
  },
  {
    name: "Hikma",
    website: "https://www.hikma.com",
    industry: Industry.PHARMA,
    country: "United Kingdom",
    employeeCount: 9100,
    revenue: 3.1,
    owner: "UKI Pharma Pod",
    notes: "Mid-to-large pharma account with visible capability-building and transformation signals.",
    stakeholders: [
      {
        name: "Rachel Moore",
        title: "Head of Commercial Excellence",
        function: "Commercial Excellence",
        buyingRole: BuyingRole.PROGRAM_OWNER,
        relevanceScore: 86,
        suggestedMessageAngle: "Low-pressure benchmark conversation around field execution and CRM workflow improvements.",
      },
      {
        name: "Omar Saleh",
        title: "CRM and Analytics Director",
        function: "Commercial Technology",
        buyingRole: BuyingRole.CHAMPION,
        relevanceScore: 82,
        suggestedMessageAngle: "Exploring whether CRM adoption and content delivery pain points are being revisited.",
      },
      {
        name: "Emily Hart",
        title: "Category Manager, Digital & Data",
        function: "Procurement",
        buyingRole: BuyingRole.PROCUREMENT,
        relevanceScore: 62,
        suggestedMessageAngle: "Confirming if any supplier discovery has started under the radar.",
      },
    ],
  },
  {
    name: "Ferring",
    website: "https://www.ferring.com",
    industry: Industry.PHARMA,
    country: "Switzerland",
    employeeCount: 7000,
    revenue: 2.3,
    owner: "Central Europe Pharma Pod",
    notes: "Global specialty pharma account with useful omnichannel and enablement adjacencies.",
    stakeholders: [
      {
        name: "Daniela Frei",
        title: "Global Launch Excellence Lead",
        function: "Launch Excellence",
        buyingRole: BuyingRole.PROGRAM_OWNER,
        relevanceScore: 88,
        suggestedMessageAngle: "Benchmarking launch readiness and field enablement before wider rollout decisions.",
      },
      {
        name: "Marc Dubois",
        title: "Digital Engagement Director",
        function: "Customer Engagement",
        buyingRole: BuyingRole.CHAMPION,
        relevanceScore: 84,
        suggestedMessageAngle: "Improving HCP engagement and compliant content orchestration in one stack.",
      },
      {
        name: "Sophie Amstad",
        title: "Senior Sourcing Manager, Platforms",
        function: "Procurement",
        buyingRole: BuyingRole.PROCUREMENT,
        relevanceScore: 63,
        suggestedMessageAngle: "Checking if platform review criteria are still being shaped.",
      },
    ],
  },
  {
    name: "Fresenius Kabi",
    website: "https://www.fresenius-kabi.com",
    industry: Industry.MEDTECH,
    country: "Germany",
    employeeCount: 43000,
    revenue: 8.5,
    owner: "DACH Medtech Pod",
    notes: "Field-heavy healthcare business with meaningful workflow and sample/consent relevance.",
    stakeholders: [
      {
        name: "Klara Vogel",
        title: "VP Field Excellence",
        function: "Field Excellence",
        buyingRole: BuyingRole.ECONOMIC_BUYER,
        relevanceScore: 90,
        suggestedMessageAngle: "Connecting field productivity gains to mobile workflows and content governance.",
      },
      {
        name: "Jan Fuchs",
        title: "Director, Sales Technology Programs",
        function: "Commercial Technology",
        buyingRole: BuyingRole.PROGRAM_OWNER,
        relevanceScore: 85,
        suggestedMessageAngle: "Comparing sample management, consent, and offline field-execution options before formal sourcing.",
      },
      {
        name: "Miriam Beck",
        title: "Head of Procurement, Commercial IT",
        function: "Procurement",
        buyingRole: BuyingRole.PROCUREMENT,
        relevanceScore: 69,
        suggestedMessageAngle: "Understanding whether an RFI path is already in motion.",
      },
    ],
  },
  {
    name: "Roche",
    website: "https://www.roche.com",
    industry: Industry.PHARMA,
    country: "Switzerland",
    employeeCount: 103000,
    revenue: 67.4,
    owner: "Strategic Pharma Pod",
    notes: "Very large account, but still useful for AI coaching and omnichannel monitoring in the demo.",
    stakeholders: [
      {
        name: "Sabine Keller",
        title: "Global Lead, Commercial Capability",
        function: "Commercial Capability",
        buyingRole: BuyingRole.PROGRAM_OWNER,
        relevanceScore: 91,
        suggestedMessageAngle: "Supporting capability programs with AI coaching and measurable field execution lift.",
      },
      {
        name: "Peter Albrecht",
        title: "Head of CRM Transformation",
        function: "Commercial Technology",
        buyingRole: BuyingRole.CHAMPION,
        relevanceScore: 86,
        suggestedMessageAngle: "Integrating coaching, engagement, and CRM workflows without adding stack friction.",
      },
      {
        name: "Isabelle Moser",
        title: "Senior Procurement Manager, Digital",
        function: "Procurement",
        buyingRole: BuyingRole.PROCUREMENT,
        relevanceScore: 67,
        suggestedMessageAngle: "Checking if capability-platform discovery is still open.",
      },
    ],
  },
  {
    name: "Bayer",
    website: "https://www.bayer.com",
    industry: Industry.PHARMA,
    country: "Germany",
    employeeCount: 100000,
    revenue: 50.7,
    owner: "Global Pharma Pod",
    notes: "Strong fit for Veeva, Salesforce, omnichannel, and commercial excellence themes.",
    stakeholders: [
      {
        name: "Theresa Klein",
        title: "Head of Omnichannel Platforms",
        function: "Omnichannel",
        buyingRole: BuyingRole.PROGRAM_OWNER,
        relevanceScore: 89,
        suggestedMessageAngle: "Benchmarking platform choices while omnichannel design is still flexible.",
      },
      {
        name: "Stefan Richter",
        title: "Global Director, Salesforce Programs",
        function: "Commercial Technology",
        buyingRole: BuyingRole.CHAMPION,
        relevanceScore: 84,
        suggestedMessageAngle: "Connecting Life Sciences Cloud programs to field adoption and coaching use cases.",
      },
      {
        name: "Lea Zimmer",
        title: "Procurement Manager, Commercial Systems",
        function: "Procurement",
        buyingRole: BuyingRole.PROCUREMENT,
        relevanceScore: 66,
        suggestedMessageAngle: "Understanding whether an internal benchmark has already narrowed the field.",
      },
    ],
  },
  {
    name: "Johnson & Johnson",
    website: "https://www.jnj.com",
    industry: Industry.MEDTECH,
    country: "United States",
    employeeCount: 131000,
    revenue: 85.2,
    owner: "Global Strategic Pod",
    notes: "Useful demo account for late-stage or post-decision scenarios.",
    stakeholders: [
      {
        name: "Megan Dorsey",
        title: "VP Sales Operations",
        function: "Sales Operations",
        buyingRole: BuyingRole.ECONOMIC_BUYER,
        relevanceScore: 88,
        suggestedMessageAngle: "Exploring whitespace after a likely platform decision in one business unit.",
      },
      {
        name: "Alex Romero",
        title: "Field Enablement Director",
        function: "Field Enablement",
        buyingRole: BuyingRole.CHAMPION,
        relevanceScore: 81,
        suggestedMessageAngle: "Finding adjacent regions or teams that still need enablement workflow improvements.",
      },
      {
        name: "Priya Nair",
        title: "Category Manager, Commercial Technology",
        function: "Procurement",
        buyingRole: BuyingRole.PROCUREMENT,
        relevanceScore: 65,
        suggestedMessageAngle: "Understanding timing for renewal windows or adjacent programs.",
      },
    ],
  },
];

export const MOCK_SIGNALS: MockSignalSeed[] = [
  {
    providerKey: "mock-public-tender",
    providerName: "Mock Public Tender Monitor",
    accountName: "Philips",
    title: "Procurement notice for digital field engagement platform review",
    description: "A mock public-sector purchasing signal references vendor selection support for field engagement, content control, and mobile presentation workflows.",
    sourceType: SourceType.TENDER_PORTAL,
    sourceName: "Mock Public Tender Monitor",
    sourceUrl: "https://example.com/mock/philips/procurement-field-engagement",
    publishedAt: isoDaysAgo(12),
    evidenceSnippet: "Vendor review mentions mobile field engagement, content governance, and CRM workflow integration.",
    recommendedAction: "Confirm whether the review covers the same field teams that use HCP or clinical-commercial engagement tools.",
    stageHint: RfpStage.ACTIVE_RFP,
    category: TargetCategory.FIELD_ENABLEMENT,
    isInferred: false,
  },
  {
    providerKey: "mock-tech-watch",
    providerName: "Mock Technology Change Watch",
    accountName: "Philips",
    title: "CRM and field content workflow consolidation initiative",
    description: "Mock monitoring suggests Philips is aligning CRM workflows, rep content delivery, and offline field execution requirements.",
    sourceType: SourceType.COMPANY_SITE,
    sourceName: "Mock Technology Change Watch",
    sourceUrl: "https://example.com/mock/philips/crm-field-workflows",
    publishedAt: isoDaysAgo(28),
    evidenceSnippet: "References consolidation of CRM-facing field content and guided workflows.",
    recommendedAction: "Lead with workflow simplification and offline/mobile field execution.",
    category: TargetCategory.CRM_ADOPTION,
  },
  {
    providerKey: "mock-hiring-feed",
    providerName: "Mock Hiring Feed",
    accountName: "Merck Healthcare",
    title: "Hiring: Global Commercial Excellence Lead",
    description: "Mock job-post export highlights commercial excellence ownership across omnichannel execution, field force effectiveness, and launch readiness.",
    sourceType: SourceType.JOB_POSTING,
    sourceName: "Mock Hiring Feed",
    sourceUrl: "https://example.com/mock/merck-healthcare/global-commercial-excellence-lead",
    publishedAt: isoDaysAgo(18),
    evidenceSnippet: "Role calls for field force effectiveness, capability-building, and cross-market execution standards.",
    recommendedAction: "Reach out to learn whether the role inherits a vendor review already in motion.",
    category: TargetCategory.COMMERCIAL_EXCELLENCE,
  },
  {
    providerKey: "mock-tech-watch",
    providerName: "Mock Technology Change Watch",
    accountName: "Merck Healthcare",
    title: "Program note mentions Veeva to Salesforce transition planning",
    description: "Mock signal from a technology watch feed suggests planning around Veeva, Salesforce, and content workflow redesign.",
    sourceType: SourceType.SEARCH_RESULT,
    sourceName: "Mock Technology Change Watch",
    sourceUrl: "https://example.com/mock/merck-healthcare/veeva-salesforce-transition",
    publishedAt: isoDaysAgo(23),
    evidenceSnippet: "Mentions phased CRM design decisions and affiliate workflow harmonization.",
    recommendedAction: "Lead with how Pitcher sits across CRM adoption, content, and field execution without forcing rip-and-replace assumptions.",
    category: TargetCategory.VEEVA_IQVIA_TRANSITION,
  },
  {
    providerKey: "mock-strategy-watch",
    providerName: "Mock Strategic Initiative Watch",
    accountName: "Merck Healthcare",
    title: "Press mention of omnichannel customer engagement transformation",
    description: "Mock press-monitoring feed highlights a broader omnichannel and HCP engagement modernization program.",
    sourceType: SourceType.PRESS_RELEASE,
    sourceName: "Mock Strategic Initiative Watch",
    sourceUrl: "https://example.com/mock/merck-healthcare/omnichannel-transformation",
    publishedAt: isoDaysAgo(34),
    evidenceSnippet: "Language points to customer engagement redesign rather than isolated channel tactics.",
    recommendedAction: "Frame Pitcher as a benchmark for connected field engagement and compliant content usage.",
    category: TargetCategory.OMNICHANNEL,
  },
  {
    providerKey: "mock-hiring-feed",
    providerName: "Mock Hiring Feed",
    accountName: "Novo Nordisk",
    title: "Job post mentions Salesforce Life Sciences Cloud capability build",
    description: "Mock ATS export references a team building Salesforce Life Sciences Cloud capabilities for global field teams.",
    sourceType: SourceType.JOB_POSTING,
    sourceName: "Mock Hiring Feed",
    sourceUrl: "https://example.com/mock/novo-nordisk/life-sciences-cloud-capability",
    publishedAt: isoDaysAgo(9),
    evidenceSnippet: "Role scope includes CRM workflow adoption, field coaching, and compliant engagement.",
    recommendedAction: "Approach as a benchmark on field adoption and HCP engagement on top of CRM change.",
    category: TargetCategory.SALESFORCE_LIFE_SCIENCES,
  },
  {
    providerKey: "mock-strategy-watch",
    providerName: "Mock Strategic Initiative Watch",
    accountName: "Novo Nordisk",
    title: "Field force effectiveness initiative referenced in leadership post",
    description: "Mock uploaded social export references a field force effectiveness initiative spanning commercial capability and HCP engagement.",
    sourceType: SourceType.UPLOADED_EXPORT,
    sourceName: "Mock Strategic Initiative Watch",
    sourceUrl: "https://example.com/mock/novo-nordisk/field-force-effectiveness",
    publishedAt: isoDaysAgo(27),
    evidenceSnippet: "Highlights rep productivity, manager coaching, and omnichannel consistency.",
    recommendedAction: "Position Pitcher as a benchmark for coaching, content, and rep execution in one workflow.",
    category: TargetCategory.COMMERCIAL_EXCELLENCE,
  },
  {
    providerKey: "mock-public-tender",
    providerName: "Mock Public Tender Monitor",
    accountName: "Novartis",
    title: "Procurement notice for HCP engagement and digital content platform",
    description: "A mock procurement notice references vendor evaluation for HCP engagement, digital content delivery, and analytics.",
    sourceType: SourceType.TENDER_PORTAL,
    sourceName: "Mock Public Tender Monitor",
    sourceUrl: "https://example.com/mock/novartis/hcp-engagement-tender",
    publishedAt: isoDaysAgo(6),
    evidenceSnippet: "Evaluation covers HCP engagement workflows, compliant content tracking, and usage analytics.",
    recommendedAction: "Move quickly to confirm whether the shortlist is still open and which business units are covered.",
    stageHint: RfpStage.ACTIVE_RFP,
    category: TargetCategory.HCP_ENGAGEMENT,
    isInferred: false,
  },
  {
    providerKey: "mock-vendor-intel",
    providerName: "Mock Vendor / Competitor Intel",
    accountName: "Novartis",
    title: "Competitor reference mentions Seismic pilot in medical affairs adjacent team",
    description: "Mock competitor-intel feed suggests Seismic was discussed in a neighboring capability workstream.",
    sourceType: SourceType.VENDOR_CASE_STUDY,
    sourceName: "Mock Vendor / Competitor Intel",
    sourceUrl: "https://example.com/mock/novartis/seismic-reference",
    publishedAt: isoDaysAgo(16),
    evidenceSnippet: "Reference points to pilot learnings around content governance and rep access.",
    recommendedAction: "Use a competitive-displacement angle and ask whether the same decision criteria apply to field teams.",
    category: TargetCategory.CONTENT_GOVERNANCE,
  },
  {
    providerKey: "mock-tech-watch",
    providerName: "Mock Technology Change Watch",
    accountName: "Hikma",
    title: "CRM workflow redesign mentioned in regional enablement update",
    description: "Mock search signal indicates Hikma may be revisiting CRM workflow adoption for field teams.",
    sourceType: SourceType.SEARCH_RESULT,
    sourceName: "Mock Technology Change Watch",
    sourceUrl: "https://example.com/mock/hikma/crm-redesign",
    publishedAt: isoDaysAgo(31),
    evidenceSnippet: "Language references CRM workflow simplification and manager visibility.",
    recommendedAction: "Start with a benchmark-led conversation rather than assuming a formal process.",
    category: TargetCategory.CRM_ADOPTION,
  },
  {
    providerKey: "mock-organizational-watch",
    providerName: "Mock Organizational Watch",
    accountName: "Hikma",
    title: "New Head of Commercial Excellence appointed",
    description: "Mock organizational signal suggests a new leader will centralize commercial capability and field execution practices.",
    sourceType: SourceType.SEARCH_RESULT,
    sourceName: "Mock Organizational Watch",
    sourceUrl: "https://example.com/mock/hikma/new-commercial-excellence-lead",
    publishedAt: isoDaysAgo(14),
    evidenceSnippet: "Leadership change references execution consistency and field productivity.",
    recommendedAction: "Map ownership and offer a benchmark conversation before new tooling assumptions settle.",
    category: TargetCategory.COMMERCIAL_EXCELLENCE,
  },
  {
    providerKey: "mock-vendor-intel",
    providerName: "Mock Vendor / Competitor Intel",
    accountName: "Ferring",
    title: "Competitor case study points to Showpad benchmark review",
    description: "Mock competitor monitoring suggests Showpad appeared in a recent benchmark conversation around launch content and sales readiness.",
    sourceType: SourceType.VENDOR_CASE_STUDY,
    sourceName: "Mock Vendor / Competitor Intel",
    sourceUrl: "https://example.com/mock/ferring/showpad-benchmark",
    publishedAt: isoDaysAgo(11),
    evidenceSnippet: "Benchmark language references launch-readiness content and rep access controls.",
    recommendedAction: "Lead with differentiation on field execution depth rather than generic content management.",
    category: TargetCategory.SALES_READINESS,
  },
  {
    providerKey: "mock-strategy-watch",
    providerName: "Mock Strategic Initiative Watch",
    accountName: "Ferring",
    title: "Launch excellence program expands omnichannel readiness scope",
    description: "Mock strategic feed suggests launch excellence leaders are expanding into omnichannel execution and manager coaching.",
    sourceType: SourceType.PRESS_RELEASE,
    sourceName: "Mock Strategic Initiative Watch",
    sourceUrl: "https://example.com/mock/ferring/launch-excellence-expansion",
    publishedAt: isoDaysAgo(22),
    evidenceSnippet: "Program scope now spans launch readiness, engagement orchestration, and analytics.",
    recommendedAction: "Position Pitcher as a practical layer connecting launch execution, content, and coaching.",
    category: TargetCategory.SALES_READINESS,
  },
  {
    providerKey: "mock-public-tender",
    providerName: "Mock Public Tender Monitor",
    accountName: "Fresenius Kabi",
    title: "RFI for sample management and field consent workflows",
    description: "A mock RFI references consent capture, sample visibility, and offline field workflow requirements.",
    sourceType: SourceType.TENDER_PORTAL,
    sourceName: "Mock Public Tender Monitor",
    sourceUrl: "https://example.com/mock/fresenius-kabi/sample-consent-rfi",
    publishedAt: isoDaysAgo(8),
    evidenceSnippet: "Requirements call out offline operation, sample workflows, and manager oversight.",
    recommendedAction: "Bring a workflow-led POV that covers consent, content, and field productivity together.",
    category: TargetCategory.SAMPLE_CONSENT,
    stageHint: RfpStage.ACTIVE_EVALUATION,
    isInferred: false,
  },
  {
    providerKey: "mock-tech-watch",
    providerName: "Mock Technology Change Watch",
    accountName: "Fresenius Kabi",
    title: "Mobile field sales app review linked to CRM modernization",
    description: "Mock technology watch indicates a broader mobile field workflow review connected to CRM modernization.",
    sourceType: SourceType.COMPANY_SITE,
    sourceName: "Mock Technology Change Watch",
    sourceUrl: "https://example.com/mock/fresenius-kabi/mobile-field-review",
    publishedAt: isoDaysAgo(19),
    evidenceSnippet: "Program language covers offline use, CRM connectivity, and compliant content access.",
    recommendedAction: "Lead with offline/mobile field execution and adoption outcomes.",
    category: TargetCategory.MOBILE_FIELD_APP,
  },
  {
    providerKey: "mock-hiring-feed",
    providerName: "Mock Hiring Feed",
    accountName: "Roche",
    title: "Hiring: AI Commercial Capability Director",
    description: "Mock job-post signal points to AI coaching, rep readiness, and field-manager capability priorities.",
    sourceType: SourceType.JOB_POSTING,
    sourceName: "Mock Hiring Feed",
    sourceUrl: "https://example.com/mock/roche/ai-commercial-capability",
    publishedAt: isoDaysAgo(13),
    evidenceSnippet: "Role covers AI coaching, capability development, and field adoption metrics.",
    recommendedAction: "Open with AI roleplay and coaching use cases that plug into existing field workflows.",
    category: TargetCategory.AI_COACHING,
  },
  {
    providerKey: "mock-vendor-intel",
    providerName: "Mock Vendor / Competitor Intel",
    accountName: "Roche",
    title: "Partner note references Mindtickle evaluation for coaching",
    description: "Mock partner monitoring suggests Mindtickle surfaced in a capability-platform review.",
    sourceType: SourceType.PARTNER_NEWS,
    sourceName: "Mock Vendor / Competitor Intel",
    sourceUrl: "https://example.com/mock/roche/mindtickle-evaluation",
    publishedAt: isoDaysAgo(24),
    evidenceSnippet: "Signal ties AI coaching evaluation to broader field execution measures.",
    recommendedAction: "Use a competitive benchmark angle and tie coaching to broader field execution and HCP engagement.",
    category: TargetCategory.AI_COACHING,
  },
  {
    providerKey: "mock-tech-watch",
    providerName: "Mock Technology Change Watch",
    accountName: "Bayer",
    title: "Veeva to Salesforce transition program referenced in regional roadmap",
    description: "Mock technology change feed suggests transition planning around Veeva workflows and Salesforce Life Sciences Cloud.",
    sourceType: SourceType.SEARCH_RESULT,
    sourceName: "Mock Technology Change Watch",
    sourceUrl: "https://example.com/mock/bayer/veeva-salesforce-roadmap",
    publishedAt: isoDaysAgo(17),
    evidenceSnippet: "Roadmap language references phased CRM change and field execution implications.",
    recommendedAction: "Position Pitcher as a stabilizing layer for adoption, content, and engagement workflows during transition.",
    category: TargetCategory.VEEVA_IQVIA_TRANSITION,
  },
  {
    providerKey: "mock-strategy-watch",
    providerName: "Mock Strategic Initiative Watch",
    accountName: "Bayer",
    title: "Omnichannel engagement transformation highlighted in internal keynote export",
    description: "Mock uploaded-export signal points to omnichannel redesign for commercial teams.",
    sourceType: SourceType.UPLOADED_EXPORT,
    sourceName: "Mock Strategic Initiative Watch",
    sourceUrl: "https://example.com/mock/bayer/omnichannel-keynote",
    publishedAt: isoDaysAgo(26),
    evidenceSnippet: "Message ties customer engagement transformation to execution consistency and analytics.",
    recommendedAction: "Start with a benchmark on omnichannel orchestration and field adoption metrics.",
    category: TargetCategory.OMNICHANNEL,
  },
  {
    providerKey: "mock-vendor-intel",
    providerName: "Mock Vendor / Competitor Intel",
    accountName: "Johnson & Johnson",
    title: "Partner announcement suggests rollout decision already made for enablement layer",
    description: "Mock partner announcement indicates a regional rollout decision may already be in execution.",
    sourceType: SourceType.PARTNER_NEWS,
    sourceName: "Mock Vendor / Competitor Intel",
    sourceUrl: "https://example.com/mock/johnson-and-johnson/enablement-rollout",
    publishedAt: isoDaysAgo(21),
    evidenceSnippet: "Announcement language suggests implementation is already underway.",
    recommendedAction: "Treat current cycle as late and hunt for adjacent regions or future renewal windows.",
    category: TargetCategory.SALES_ENABLEMENT,
    stageHint: RfpStage.POST_DECISION,
  },
  {
    providerKey: "mock-organizational-watch",
    providerName: "Mock Organizational Watch",
    accountName: "Johnson & Johnson",
    title: "Sales operations centralization follows regional rollout",
    description: "Mock organizational signal suggests central teams are now standardizing around an already selected platform direction.",
    sourceType: SourceType.SEARCH_RESULT,
    sourceName: "Mock Organizational Watch",
    sourceUrl: "https://example.com/mock/johnson-and-johnson/sales-ops-centralization",
    publishedAt: isoDaysAgo(35),
    evidenceSnippet: "Signal references centralization after program decisions were made.",
    recommendedAction: "Map whitespace in adjacent business units rather than pushing the current cycle.",
    category: TargetCategory.COMMERCIAL_EXCELLENCE,
  },
];

export const MOCK_PROVIDER_RUNS = [
  {
    providerKey: "mock-hiring-feed",
    providerName: "Mock Hiring Feed",
    status: ProviderRunStatus.SUCCESS,
    summary: "Scanned mock hiring signals for capability, CRM, and enablement roles.",
    accountsScanned: 10,
    signalsCreated: 5,
    startedAt: isoDaysAgo(1),
    finishedAt: isoDaysAgo(1),
  },
  {
    providerKey: "mock-tech-watch",
    providerName: "Mock Technology Change Watch",
    status: ProviderRunStatus.SUCCESS,
    summary: "Checked mock CRM, Veeva, Salesforce, and content-platform change signals.",
    accountsScanned: 10,
    signalsCreated: 6,
    startedAt: isoDaysAgo(1),
    finishedAt: isoDaysAgo(1),
  },
  {
    providerKey: "mock-strategy-watch",
    providerName: "Mock Strategic Initiative Watch",
    status: ProviderRunStatus.SUCCESS,
    summary: "Reviewed mock strategic and transformation narratives across target accounts.",
    accountsScanned: 10,
    signalsCreated: 5,
    startedAt: isoDaysAgo(2),
    finishedAt: isoDaysAgo(2),
  },
  {
    providerKey: "mock-vendor-intel",
    providerName: "Mock Vendor / Competitor Intel",
    status: ProviderRunStatus.PARTIAL,
    summary: "Collected mock competitor and partner-reference signals; one source returned partial coverage.",
    accountsScanned: 10,
    signalsCreated: 4,
    startedAt: isoDaysAgo(2),
    finishedAt: isoDaysAgo(2),
  },
  {
    providerKey: "mock-public-tender",
    providerName: "Mock Public Tender Monitor",
    status: ProviderRunStatus.SUCCESS,
    summary: "Ingested mock tender, RFI, and procurement notices.",
    accountsScanned: 10,
    signalsCreated: 4,
    startedAt: isoDaysAgo(3),
    finishedAt: isoDaysAgo(3),
  },
];
